import { expect,test } from '@playwright/test'
test('loads a valid theme and exposes the authoring workspace',async({page})=>{
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'Y2ThemeStudio'})).toBeVisible()
  await expect(page.locator('canvas')).toHaveScreenshot('neon-grid-editor.png',{maxDiffPixelRatio:.02})
  await expect(page).toHaveScreenshot('workspace.png',{maxDiffPixelRatio:.02})
  await expect(page.getByText('Theme is valid and ready to export.')).toBeVisible()
  await page.getByLabel('Template').selectOption({label:'Pixel Garden'})
  await expect(page.getByText('Pixel Garden loaded')).toBeVisible()
  await page.locator('.layers button').first().click()
  await expect(page.getByRole('heading',{name:'Inspector'})).toBeVisible()
  await page.getByRole('button',{name:'JSON'}).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('dialog').getByRole('button',{name:'Close'}).click()
  const png=page.waitForEvent('download')
  await page.getByRole('button',{name:'PNG'}).click()
  expect((await png).suggestedFilename()).toBe('pixel-garden-remix-main_menu.png')
  const zip=page.waitForEvent('download')
  await page.getByRole('button',{name:'Export ZIP'}).click()
  expect((await zip).suggestedFilename()).toBe('pixel-garden-remix.zip')
  await expect(page.getByText('Theme ZIP exported')).toBeVisible()
  await expect(page.locator('link[rel=manifest]')).toHaveAttribute('href','./manifest.webmanifest')
})
